# Generated by Django 2.2 on 2019-06-12 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmanuscript',
            name='PDF_file',
        ),
        migrations.CreateModel(
            name='PDF_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='default.jpg', upload_to='Manuscript_Files')),
                ('manuscript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.newManuscript')),
            ],
        ),
    ]
