# Generated by Django 2.2 on 2019-06-12 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190612_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_files',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.newManuscript'),
        ),
    ]
