# Generated by Django 2.2 on 2019-06-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190613_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmanuscript',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='Manuscript_Files'),
        ),
    ]
