# Generated by Django 2.2 on 2019-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_newmanuscript_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmanuscript',
            name='fileImg',
            field=models.FileField(default='default.jpg', upload_to='Manuscript_Files'),
        ),
    ]
