# Generated by Django 2.2 on 2019-06-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_newmanuscript_fileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmanuscript',
            name='fileImg',
            field=models.FileField(default='Cover.jpg', upload_to='Manuscript_Files'),
        ),
    ]
